### ISSUE TITLE
Comments - Tanya

### ISSUE THREAD

**Issue by TanyaS08** [FrancisBanville/ms_interpreting_probabilities#25]
Tanya has ideas and thoughts (not big ones though)

**Comment by TanyaS08** [comment]
One general comment is the use of local, realised, regional, potential. In the text you tend to use potential and local as opposites. Is it not perhaps better to pair it as local - regional and realised - potential. It's a very nitty comment but I feel like the local - potential pairing is referring to different aspects. Personally I like regional - local since it links more explicitly to the scale we are thinking at.

**Comment by FrancisBanville** [comment]
The only other ‘big’ comment she has is that when we define p(x, y, z) for the first time it might be worth specify what xyz represent. Z wasnt immediately clear to her.
