### ISSUE TITLE
Conceptual figure

### ISSUE THREAD

**Issue by FrancisBanville** [FrancisBanville/ms_interpreting_probabilities#3]
Make a conceptual figure illustrating the relationship between metawebs and local networks. Show the spatial (e.g., patches) and temporal (e.g., seasons, time of the day, time series) variations of local interactions in response to environmental variables.

The conceptual figure could be like a graphical abstract describing all sections and figures in the manuscript. It should thus be done last. 

### Additional ideas: 

The conceptual figure could also show:
- the spatiotemporal scaling of potential and local interactions 
- the spatial sampling of probabilistic interactions (potential and local) into Boolean networks
- the taxonomic scaling of interactions (how a scale-up of the node from the individual to the population and species levels changes our interpretation of probabilistic interactions)

**Comment by tpoisot** [comment]
Good idea, we can maybe adapt  https://images.app.goo.gl/s1rqrTNqvV1GdeBdA

**Comment by FrancisBanville** [comment]
Closing this issue after we agreed it might not be super useful after all.
